### ISSUE TITLE
Build on iOS

### ISSUE THREAD

**Issue by MasoudRashidi** [adtrace/adtrace_sdk_flutter#12]
I try to build iOS version on simulator but I get this error after I add adtrace_sdk_flutter package.

My Flutter sdk version is : 3.24.1

And I'm using adtrace_sdk_flutter: ^1.5.0 

The error message is below:

Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           12.7s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'adtrace_sdk_flutter.AdTraceSdkDelegate': '/Users/masoudrashidizadeh/projects/flutter/jwaan/stylist-app/build/ios/Debug-iphonesimulator/Adtrace-sdk/Adtrace_sdk.framework/Headers/Adtrace.h'
/Users/masoudrashidizadeh/.pub-cache/hosted/pub.dev/adtrace_sdk_flutter-1.5.0/ios/Classes/AdTraceSdkDelegate.h:1:8

Parse Issue (Xcode): Could not build module 'adtrace_sdk_flutter'
/Users/masoudrashidizadeh/projects/flutter/jwaan/stylist-app/ios/Runner/GeneratedPluginRegistrant.m:9:8

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

**Comment by namini40** [comment]
Hello @MasoudRashidi 
please take look at [this](https://github.com/adtrace/adtrace_sdk_flutter/issues/5)
feel free to ask if the issue still remains or anything.

**Comment by namini40** [comment]
I am closing the issue since it's related to an older one.
